// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	payment "payment/cmd/api/internal/handler/payment"
	"payment/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/orders/:order_serial_number/payment",
				Handler: payment.CreatePaymentHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Jwt.AccessSecret),
		rest.WithPrefix("/payment"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/orders/payments/notice",
				Handler: payment.OrderPaymentNoticeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/payment"),
	)
}
