// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrderPaymentNotice = "greet_order_payment_notice"

// OrderPaymentNotice mapped from table <greet_order_payment_notice>
type OrderPaymentNotice struct {
	ID                  int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	PaymentSerialNumber string         `gorm:"column:payment_serial_number;type:varchar(32);not null;comment:支付订单号" json:"payment_serial_number"`
	ThirdNotice         string        `gorm:"column:third_notice;type:text;comment:第三方通知结果" json:"third_notice"`
	DeletedAt           gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;default:null;" json:"deleted_at"`
	CreatedAt           *time.Time     `gorm:"column:created_at;type:time stamp" json:"created_at"`
	UpdatedAt           *time.Time     `gorm:"column:updated_at;type:timestamp" json:"updated_at"`
}

// TableName OrderPaymentNotice's table name
func (*OrderPaymentNotice) TableName() string {
	return TableNameOrderPaymentNotice
}
